In [8]:
import numpy as np

"""
Exercise 4: NumPy Array Operations
Complete the following tasks using NumPy.
"""

# Task 1: Create a 5x5 matrix where border elements are 1 and interior is 0
# (5 points)
# TODO: Create the matrix described above
# Hint: Use np.ones and array slicing

print("Task 1:")
# Task 1: Create a 5x5 matrix where border elements are 1 and interior is 0
# Create a 5x5 matrix of ones
matrix = np.ones((5, 5))

#using array slicing
matrix[1:4, 1:4] = 0
print(matrix)

# Task 2: Normalise a random array
# (5 points)
np.random.seed(42)
random_data = np.random.randn(100, 3)
# TODO: Normalize each column to have mean=0 and std=1

print("Task 2:")

normalized_data = (random_data - random_data.mean(axis=0)) / random_data.std(axis=0)

#Output Normalized means and std
print("Normalized means (<=> 0):", normalized_data.mean(axis=0))
print("Normalized std (<=> 1):", normalized_data.std(axis=0))


# Task 3: Implement linear regression solution using normal equation
# (10 points)
# Given X (features) and y (target), compute theta
# theta = (X^T X)^(-1) X^T y
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1
# TODO: Calculate theta_hat using the normal equation
# TODO: Print the estimated coefficients and compare with true_theta

print("Task 3:")
# Task 3: Implement linear regression solution using normal equation
y = X @ true_theta + np.random.randn(50) * 0.1

# Finding the transpose of X using .T
X_T = X.T
# Step 2: Perform matrix multiplication using the @ symbol
X_T_X = X_T @ X
# Step 3: Compute the matrix inverse using np.linalg.inv
X_T_X_inv = np.linalg.inv(X_T_X)
# Step 4: isolating the weight coefficients
theta_hat = X_T_X_inv @ X_T @ y

print("The True Theta is:", true_theta)
print("The Estimated Theta is:", theta_hat)

Task 1:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Task 2:
Normalized means (<=> 0): [-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
Normalized std (<=> 1): [1. 1. 1.]
Task 3:
The True Theta is: [ 2.5 -1.2  3.7]
The Estimated Theta is: [ 2.46515136 -1.21272974  3.68234017]
